yarnPath: .yarn/releases/yarn-3.4.0.cjs

nodeLinker: node-modules

npmScopes:
  taskforcesh:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TASKFORCESH_TOKEN}"
    npmRegistryServer: "https://npm.taskforce.sh/"